GET http://localhost:5068

###
POST  http://localhost:5068/login

###

GET http://localhost:5068/account-api/

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQm9iIiwiZXhwIjoxNjc0OTczNzg5LCJpc3MiOiJwcmFjdGljYWwgYXNwbmV0Y29yZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwNjgvIn0.IqkNE8hLejZ26ZDVu0YQajrqVIm3CC6IXUxTnIKNT9o

###

GET http://localhost:5068/app-api/